apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.133.0
        - name: myapp
          image: openjdk:21-jdk
          volumeMounts:
            - mountPath: /var/local
              name: myapp-volume
              readOnly: true
          command: ["java", "-javaagent:/var/local/otel-agent.jar", "-jar", "/var/local/myapp.jar"]
      volumes:
        - name: myapp-volume
          hostPath:
            path: /apps
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: myapp
  sessionAffinity: None
  type: LoadBalancer