plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

configurations {
    otelAgent
}

dependencies {
    otelAgent("io.opentelemetry.javaagent:opentelemetry-javaagent:2.19.0")
}

test {
    useJUnitPlatform()
}

tasks.register("copyApps", Copy) {
    subprojects.each { subproject ->
        dependsOn(":${subproject.projectDir.getName()}:build")
        from("${subproject.projectDir}/build/libs") {
            include "app.jar"
            rename ".*app.jar", "${subproject.projectDir.getName()}.jar"
        }
        into "${rootDir}/build/libs"
    }
}

tasks.register('copyAgent', Copy) {
    from(configurations.otelAgent) {
        rename '.*.jar', 'otel-agent.jar'
    }
    into "${rootDir}/build/libs"
}

build.finalizedBy("copyAgent")
build.finalizedBy("copyApps")