services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-data:/loki
      - ./loki-config.yml:/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  otel-collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command:
      - "--config=/otel-collector-config.yaml"
    depends_on:
      - loki
    volumes:
      - ./otel-collector-config.yml:/otel-collector-config.yaml
    ports:
      - "4318" # OTLP HTTP port

  myapp:
    image: openjdk:21-jdk
    container_name: myapp
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
      MY_TEST_VAR: "Hello World"
    entrypoint: java -javaagent:/var/local/otel-agent.jar -jar /var/local/myapp.jar
    ports:
      - "8080:8080"
    volumes:
      - ./build/libs:/var/local
    depends_on:
      - otel-collector

