services:

#
# Observability stack
#

  grafana:
    image: grafana/grafana:12.1.0
    container_name: grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - tempo
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  loki:
    image: grafana/loki:3.1.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./data/loki:/loki
      - ./config/loki/loki-config.yml:/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:2.8.2
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
      - ./data/tempo:/var/tempo
    ports:
      - "3200" # tempo
      - "4317" # otlp grpc

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/prometheus.yml
    command:
      - "--config.file=/prometheus.yml"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=native-histograms"

  otel-collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.134.1
    container_name: otel-collector
    command:
      - "--config=/otel-collector-config.yaml"
    depends_on:
      - loki
      - tempo
    volumes:
      - ./config/otel-collector/otel-collector-config.yml:/otel-collector-config.yaml
    ports:
      - "4318" # OTLP HTTP port
      - "9090:9090"


#
# Infra
#

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  mysql:
    image: mysql:8.4.6
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devfest2025

#
# Application stack
#

  galactic-empire:
    image: openjdk:21-jdk
    container_name: galactic-empire
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
    entrypoint: java -javaagent:/var/local/otel-agent.jar -jar /var/local/galactic-empire.jar
    ports:
      - "8080:8080"
    volumes:
      - ./build/libs:/var/local
    depends_on:
      - rabbitmq
      - otel-collector
      - mysql

  clone-factory:
    image: openjdk:21-jdk
    container_name: clone-factory
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
    entrypoint: java -javaagent:/var/local/otel-agent.jar -jar /var/local/clone-factory.jar
    volumes:
      - ./build/libs:/var/local
    depends_on:
      - rabbitmq
      - otel-collector
      - mysql

